<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-AUQI9P7" failures="1" tests="8" name="com.Day19.AlertsAndModals.TestNG.BootstrapAlertTest" time="6.880" errors="0" timestamp="11 Aug 2021 12:47:40 GMT">
  <testcase classname="com.Day19.AlertsAndModals.TestNG.BootstrapAlertTest" name="TC_ID_06_verifyAutoCloseabledangerMessage" time="0.142"/>
  <testcase classname="com.Day19.AlertsAndModals.TestNG.BootstrapAlertTest" name="TC_ID_04_verifyAutoCloseableWarningMessage" time="0.147"/>
  <testcase classname="com.Day19.AlertsAndModals.TestNG.BootstrapAlertTest" name="TC_ID_03_verifyNormalSuccessMessage" time="0.189"/>
  <testcase classname="com.Day19.AlertsAndModals.TestNG.BootstrapAlertTest" name="TC_ID_01_verifyBootstrapAlertHomePage" time="5.713"/>
  <testcase classname="com.Day19.AlertsAndModals.TestNG.BootstrapAlertTest" name="TC_ID_07_verifyNormaDangerMessage" time="0.188"/>
  <testcase classname="com.Day19.AlertsAndModals.TestNG.BootstrapAlertTest" name="TC_ID_05_verifyNormalWarningMessage" time="0.158"/>
  <testcase classname="com.Day19.AlertsAndModals.TestNG.BootstrapAlertTest" name="TC_ID_02_verifyAutocloseableableSuccessMessage" time="0.183"/>
  <testcase classname="com.Day19.AlertsAndModals.TestNG.BootstrapAlertTest" name="TC_ID_08_verifyAutoCloseableInfoMessage" time="0.160">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.Day19.AlertsAndModals.TestNG.BootstrapAlertPage.verifyAutocloseableInfoMsgIsDisplayedOrNot(BootstrapAlertPage.java:237)
	at com.Day19.AlertsAndModals.TestNG.BootstrapAlertTest.TC_ID_08_verifyAutoCloseableInfoMessage(BootstrapAlertTest.java:78)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC_ID_08_verifyAutoCloseableInfoMessage -->
</testsuite> <!-- com.Day19.AlertsAndModals.TestNG.BootstrapAlertTest -->
